---
#- name: Ensure Apache is installed
  hosts: 172.31.87.141
  become: yes
  tasks:
    - name: install apache server
      yum:
        name: httpd
        state: present
    - name: start and enable
      service:
        name: httpd
        state: started
        enabled: yes

